scalar DateTime

type User {
  int: String!,
  name: String!,
  lastName: String!,
  email: String!,
  birthDate: DateTime!,
  country: String!,
  lookingForWork: Boolean,
  profileImage: String
  githubUser: String!,
  roles: [String!]!
  level: String
  experiences: [String!]!
  technologies: [String!]!
  createdAt: DateTime
  updatedAt: DateTime
}

input RegisterUserInput {
  int: String!,
  name: String!,
  lastName: String!,
  email: String!,
  birthDate: DateTime!,
  country: String!,
  lookingForWork: Boolean,
  profileImage: String
  githubUser: String!,
  roles: [String!]!
  level: String
  experiences: [String!]!
  technologies: [String!]!
}

type Query {
    getProfile: String
}

type Mutation {
    registerUser: String!
}