import { ReactNode } from 'react'
import './globals.css'
import { Inter, Righteous } from 'next/font/google'
import { Provider } from '@/components/layout/auth/Provider'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '500', '700'],
})
const righteous = Righteous({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-righteous',
})

export const metadata = {
  title: 'Ymir',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="antialiased">
      <body
        className={`
          ${inter.variable} ${righteous.variable} 
          scroll-smooth bg-gray-800 font-sans text-gray-50 scrollbar-thin scrollbar-track-gray-900 scrollbar-thumb-gray-500
        `}
      >
        <Provider>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  )
}
