import { ReactNode } from 'react'
import './globals.css'
import { Roboto, Righteous } from 'next/font/google'
import { Header } from '@/components/Header'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['400', '500', '700'],
})
const righteous = Righteous({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-righteous',
})

export const metadata = {
  title: 'Ymir',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`
          ${roboto.variable} ${righteous.variable} font-sans bg-gray-700 text-gray-100
          scrollbar-thin scroll-smooth scrollbar-track-gray-800 scrollbar-thumb-gray-500
        `}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
