import { ReactNode } from 'react'
import './globals.css'
import { Inter, Righteous } from 'next/font/google'
import { Header } from '@/components/Header'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '500', '700'],
})
const righteous = Righteous({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-righteous',
})

export const metadata = {
  title: 'Ymir',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`
          ${inter.variable} ${righteous.variable} scroll-smooth bg-gray-700 font-sans
          text-gray-100 scrollbar-thin scrollbar-track-gray-800 scrollbar-thumb-gray-500
        `}
      >
        <div>
          <Header />
          <main>{children}</main>
        </div>
      </body>
    </html>
  )
}
