version: '3'

services:
  ymir-pg:
    image: bitnami/postgresql
    restart: always
    ports:
      - 5100:5432
    environment:
      - POSTGRESQL_USERNAME=${PG_USER}
      - POSTGRESQL_PASSWORD=${PG_PASSWORD}
      - POSTGRESQL_DATABASE=${PG_DATABASE}